services:
  reservation-service:
    build:
      context: ./reservation-service
    image:
      ksah3756/craftcoder-reservation-service:latest
    container_name: reservation-service
    ports:
      - 8080:8080

  subscription-service:
    build:
      context: ./subscription-service
    image:
      ksah3756/craftcoder-subscription-service:latest
    container_name: subscription-service
    ports:
      - 8081:8081

  mysql:
    image: mysql:8.0.26
    container_name: mysql
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
